version: '2'
services:

  test2:
    image: python:2-alpine
    volumes:
      - '.:/opt/code'
    working_dir: '/opt/code'
    command: 'sh -c "pip install . && baroness --help"'

  test3:
    image: python:3-alpine
    volumes:
      - '.:/opt/code'
    working_dir: '/opt/code'
    command: 'sh -c "pip install . && baroness --help"'
