version: '2'
services:

  test2:
    image: python:2-alpine
    volumes:
      - '.:/opt/code'
    working_dir: '/opt/code'
    command: 'sh -c "pip install . -r requirements_test.txt && baroness --help && py.test"'

  test3:
    image: python:3-alpine
    volumes:
      - '.:/opt/code'
    working_dir: '/opt/code'
    command: 'sh -c "pip install . -r requirements_test.txt && baroness --help && py.test"'
